#!/bin/sh

# Check if Gemfile.lock was changed in the merge
if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep --quiet "Gemfile.lock"; then
  echo "Gemfile.lock updated, running bundle..."
  bundle install
fi
